### ISSUE TITLE
Bot Responds to Other Bots

### ISSUE THREAD

**Issue by modelmat** [bwmarrin/disgord#2]
This is a bad idea, and should never be allowed. Most user objects will have a bot or similar property

**Comment by bwmarrin** [comment]
Weird, I guess I've never noticed this ticket here.

In any event, this is an interesting talking point.  Some people would argue that bots talking to each other can be pretty entertaining.  I suppose I agree that ignoring other bots is probably a safe decision to make and I'll look at adjusting the command router to do that.
